export const GET_EDUCATIONS = "GET_EDUCATIONS";
export const EDUCATIONS_ERROR = "EDUCATIONS_ERROR";
export const EDUCATIONS_LOADING = "EDUCATIONS_LOADING";
export const CLEAR_EDUCATIONS = "CLEAR_EDUCATIONS";
export const IS_FETCHING = "IS_FETCHING";
export const ITEMS_FETCHING = "ITEMS_FETCHING";
export const SWITCH_PRICE = "SWITCH_PRICE";
export const FILTER_FIELD = "FILTER_FIELD";